### ISSUE TITLE
Molecular weight error

### ISSUE THREAD

**Issue by hlasimpk** [rigdenlab/SIMBAD#95]
## General Information

- SIMBAD version: 0.1.10
- Python version: ccp4-python
- Environment (if applicable): <ADD HERE>

## Example

A minimal example to reproduce the error:
```
simbad-morda -morda_db <path> <mtz>

Very difficult to trace back error because it only occurs sometimes. Got the error submitted from a user and Eugene also got the error, although I've not been able to recreate the error. 
```

## Traceback

The Python traceback
```
SIMBAD EXITING AT...
Traceback (most recent call last):
  File "/home/tom/bin/destination/ccp4-7.0/lib/py2/simbad/command_line/simbad_morda.py", line 92, in <module>
    main()
  File "/home/tom/bin/destination/ccp4-7.0/lib/py2/simbad/command_line/simbad_morda.py", line 66, in main
    solution_found = simbad.command_line._simbad_morda_search(args)
  File "/home/tom/bin/destination/ccp4-7.0/lib/py2/simbad/command_line/__init__.py", line 358, in _simbad_morda_search
    chunk_size=args.chunk_size)
  File "/home/tom/bin/destination/ccp4-7.0/lib/py2/simbad/rotsearch/amore_search.py", line 146, in run
    solvent_content = sol_calc.calculate_from_struct(pdb_struct)
  File "/home/tom/bin/destination/ccp4-7.0/lib/py2/simbad/util/matthews_coef.py", line 34, in calculate_from_struct
    return self._calculate(struct.molecular_weight)
  File "/home/tom/bin/destination/ccp4-7.0/lib/py2/simbad/util/matthews_coef.py", line 37, in _calculate
    return self.dens_calc.solvent_fraction(mw, 0.74) * 100
  File "/home/tom/bin/destination/ccp4-7.0/lib/py2/site-packages/cctbx_project/mmtbx/scaling/matthews.py", line 56, in solvent_fraction
    rho_spec = rho_spec)
  File "/home/tom/bin/destination/ccp4-7.0/lib/py2/site-packages/cctbx_project/mmtbx/scaling/matthews.py", line 51, in macromolecule_fraction
    return rho_spec / ( 0.602 * self.vm( weight = weight ) )
  File "/home/tom/bin/destination/ccp4-7.0/lib/py2/site-packages/cctbx_project/mmtbx/scaling/matthews.py", line 47, in vm
    raise ValueError, "Incorrect weight"
ValueError: Incorrect weight
```

**Comment by hlasimpk** [comment]
This has been fixed in newer version.
